apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: task-manager
spec:
  selector:
    app: database-service
  ports:
    - port: 8081
      targetPort: 8081
  # ClusterIP — only reachable by backend-service inside the cluster
  type: ClusterIP
